HOST = "127.0.0.1"
START_PORT = 8000
PORT_SEARCH_COUNT = 100

HTML_FILE = "src/index.html"
OPINET_CONFIG_FILE = "opinet_API.json"

OPINET_DETAIL_URL = "https://www.opinet.co.kr/api/detailById.do"
OPINET_REQUEST_TIMEOUT_SECONDS = 12
OPINET_MAX_WORKERS = 5

PRODUCT_NAMES = {
    "B027": "휘발유",
    "D047": "경유",
}

BROWSER_REOPEN_COOLDOWN_SECONDS = 30
HEARTBEAT_TIMEOUT_SECONDS = 10
STARTUP_GRACE_SECONDS = 30
CLOSE_GRACE_SECONDS = 5

AUTOSTART_NAME = "DailyBoard"
MUTEX_NAME = "Local\\DailyBoardLauncherSingleton"

ERROR_ALREADY_EXISTS = 183
SW_SHOWNORMAL = 1
